name: Test microphone dialog box bug

on:
  push:
  workflow_dispatch:
jobs:
  macos:
    runs-on: ${{ matrix.runner }}

    strategy:
      fail-fast: false
      matrix:
        runner: [macos-latest, macos-13, macos-14, macos-15]

    steps:
      - name: Play a sound
        timeout-minutes: 2
        run: |
          (sleep 10; screencapture debugscreen_${{ matrix.runner }}.png) &
          afplay /System/Library/Sounds/Funk.aiff
          sleep 20

      - name: Publish debug screenshot
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: debugscreen_${{ matrix.runner }}.png
          path: debugscreen_${{ matrix.runner }}.png

